version: 0.2

env:
  parameter-store:
    ECR_REGISTRY: /myapp/docker-registry/url

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      - echo "Installing dependencies..."
      - pip install -r simple-python-app/requirements.txt

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_REGISTRY/simple-python-flask-app:latest simple-python-app/
      - docker push $ECR_REGISTRY

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: simple-python-app



